import { cp, rm, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { generateSW } from 'workbox-build';
import { pwaOptions } from '../pwa.config';
// Deploy only static output. The existing Worker continues to own /api/*.
const privacy = await readFile('.output/public/privacy/index.html', 'utf8');
if (!privacy.includes('Optional Google Drive backup')) throw new Error('Privacy prerender missing');
await rm('dist', { recursive: true, force: true });
await cp('.output/public', 'dist', { recursive: true });
// Permit only the exact inline hydration scripts generated by this build.
const hashes = new Set<string>();
for (const file of ['index.html', 'privacy/index.html']) {
  const html = await readFile(`dist/${file}`, 'utf8');
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (!/\bsrc\s*=/.test(match[1]) && match[2])
      hashes.add(`'sha256-${createHash('sha256').update(match[2]).digest('base64')}'`);
  }
}
const headers = await readFile('dist/_headers', 'utf8');
await writeFile(
  'dist/_headers',
  headers.replace("script-src 'self'", `script-src 'self' ${[...hashes].join(' ')}`),
);
// Prerendering finishes after Vite's client build. Include the final HTML in precache.
const { warnings } = await generateSW({
  ...pwaOptions.workbox,
  globDirectory: 'dist',
  swDest: 'dist/sw.js',
  // Workbox maps /privacy/ to its index, but the router also links to /privacy.
  additionalManifestEntries: [
    { url: '/privacy', revision: createHash('sha256').update(privacy).digest('hex') },
  ],
  cleanupOutdatedCaches: true,
  clientsClaim: true,
});
for (const warning of warnings) console.warn(warning);
